/*
 * keyboard.c
 *
 *  Created on: Sep 18, 2023
 *      Author: matt
 */

#include "keyboard.h"
#include "NUC100Series.h"
#include <string.h>

#define KEYBOARD_KEY_COUNT 8
#define KEYBOARD_DELAY_LOOP_COUNT 10
#define KEYBOARD_DELAY() delay = KEYBOARD_DELAY_LOOP_COUNT; while(--delay){}
#define KEYBOARD_TIMER TIMER1
#define KEYBOARD_TIMER_MODULE TMR1_MODULE
#define KEYBOARD_VELOCITY_RATE_MS 60000

// KEY DEFINITIONS

#define KEYBOARD_KEY1 PB8
#define KEYBOARD_KEY1_PORT PB
#define KEYBOARD_KEY1_PORT_VAL 1
#define KEYBOARD_KEY1_PIN 8

#define KEYBOARD_KEY2 PB9
#define KEYBOARD_KEY2_PORT PB
#define KEYBOARD_KEY2_PORT_VAL 1
#define KEYBOARD_KEY2_PIN 9

#define KEYBOARD_KEY3 PB10
#define KEYBOARD_KEY3_PORT PB
#define KEYBOARD_KEY3_PORT_VAL 1
#define KEYBOARD_KEY3_PIN 10

#define KEYBOARD_KEY4 PB11
#define KEYBOARD_KEY4_PORT PB
#define KEYBOARD_KEY4_PORT_VAL 1
#define KEYBOARD_KEY4_PIN 11

#define KEYBOARD_KEY5 PB12
#define KEYBOARD_KEY5_PORT PB
#define KEYBOARD_KEY5_PORT_VAL 1
#define KEYBOARD_KEY5_PIN 12

#define KEYBOARD_KEY6 PB13
#define KEYBOARD_KEY6_PORT PB
#define KEYBOARD_KEY6_PORT_VAL 1
#define KEYBOARD_KEY6_PIN 13

#define KEYBOARD_KEY7 PB14
#define KEYBOARD_KEY7_PORT PB
#define KEYBOARD_KEY7_PORT_VAL 1
#define KEYBOARD_KEY7_PIN 14

#define KEYBOARD_KEY8 PB15
#define KEYBOARD_KEY8_PORT PB
#define KEYBOARD_KEY8_PORT_VAL 1
#define KEYBOARD_KEY8_PIN 15

// GROUP DEFINITIONS

#define KEYBOARD_DETECT_GROUP1 PC1
#define KEYBOARD_DETECT_GROUP1_PORT PC
#define KEYBOARD_DETECT_GROUP1_PORT_VAL 2
#define KEYBOARD_DETECT_GROUP1_PIN 1
#define KEYBOARD_PRESS_GROUP1 PC0
#define KEYBOARD_PRESS_GROUP1_PORT PC
#define KEYBOARD_PRESS_GROUP1_PORT_VAL 2
#define KEYBOARD_PRESS_GROUP1_PIN 0

#define KEYBOARD_DETECT_GROUP2 PC3
#define KEYBOARD_DETECT_GROUP2_PORT PC
#define KEYBOARD_DETECT_GROUP2_PORT_VAL 2
#define KEYBOARD_DETECT_GROUP2_PIN 3
#define KEYBOARD_PRESS_GROUP2 PC2
#define KEYBOARD_PRESS_GROUP2_PORT PC
#define KEYBOARD_PRESS_GROUP2_PORT_VAL 2
#define KEYBOARD_PRESS_GROUP2_PIN 2

#define KEYBOARD_DETECT_GROUP3 PC7
#define KEYBOARD_DETECT_GROUP3_PORT PC
#define KEYBOARD_DETECT_GROUP3_PORT_VAL 2
#define KEYBOARD_DETECT_GROUP3_PIN 7
#define KEYBOARD_PRESS_GROUP3 PC6
#define KEYBOARD_PRESS_GROUP3_PORT PC
#define KEYBOARD_PRESS_GROUP3_PORT_VAL 2
#define KEYBOARD_PRESS_GROUP3_PIN 6

#define KEYBOARD_DETECT_GROUP4 PC9
#define KEYBOARD_DETECT_GROUP4_PORT PC
#define KEYBOARD_DETECT_GROUP4_PORT_VAL 2
#define KEYBOARD_DETECT_GROUP4_PIN 9
#define KEYBOARD_PRESS_GROUP4 PC8
#define KEYBOARD_PRESS_GROUP4_PORT PC
#define KEYBOARD_PRESS_GROUP4_PORT_VAL 2
#define KEYBOARD_PRESS_GROUP4_PIN 8

#define KEYBOARD_DETECT_GROUP5 PC11
#define KEYBOARD_DETECT_GROUP5_PORT PC
#define KEYBOARD_DETECT_GROUP5_PORT_VAL 2
#define KEYBOARD_DETECT_GROUP5_PIN 11
#define KEYBOARD_PRESS_GROUP5 PC10
#define KEYBOARD_PRESS_GROUP5_PORT PC
#define KEYBOARD_PRESS_GROUP5_PORT_VAL 2
#define KEYBOARD_PRESS_GROUP5_PIN 10

#define KEYBOARD_DETECT_GROUP6 PC15
#define KEYBOARD_DETECT_GROUP6_PORT PC
#define KEYBOARD_DETECT_GROUP6_PORT_VAL 2
#define KEYBOARD_DETECT_GROUP6_PIN 15
#define KEYBOARD_PRESS_GROUP6 PC14
#define KEYBOARD_PRESS_GROUP6_PORT PC
#define KEYBOARD_PRESS_GROUP6_PORT_VAL 2
#define KEYBOARD_PRESS_GROUP6_PIN 14

#define KEYBOARD_DETECT_GROUP7 PB1
#define KEYBOARD_DETECT_GROUP7_PORT PB
#define KEYBOARD_DETECT_GROUP7_PORT_VAL 1
#define KEYBOARD_DETECT_GROUP7_PIN 1
#define KEYBOARD_PRESS_GROUP7 PB0
#define KEYBOARD_PRESS_GROUP7_PORT PB
#define KEYBOARD_PRESS_GROUP7_PORT_VAL 1
#define KEYBOARD_PRESS_GROUP7_PIN 0

#define KEYBOARD_DETECT_GROUP8 PB3
#define KEYBOARD_DETECT_GROUP8_PORT PB
#define KEYBOARD_DETECT_GROUP8_PORT_VAL 1
#define KEYBOARD_DETECT_GROUP8_PIN 3
#define KEYBOARD_PRESS_GROUP8 PB2
#define KEYBOARD_PRESS_GROUP8_PORT PB
#define KEYBOARD_PRESS_GROUP8_PORT_VAL 1
#define KEYBOARD_PRESS_GROUP8_PIN 2

#define KEYBOARD_DETECT_GROUP9 PA11
#define KEYBOARD_DETECT_GROUP9_PORT PA
#define KEYBOARD_DETECT_GROUP9_PORT_VAL 0
#define KEYBOARD_DETECT_GROUP9_PIN 11
#define KEYBOARD_PRESS_GROUP9 PA10
#define KEYBOARD_PRESS_GROUP9_PORT PA
#define KEYBOARD_PRESS_GROUP9_PORT_VAL 0
#define KEYBOARD_PRESS_GROUP9_PIN 10

#define KEYBOARD_DETECT_GROUP10 PA13
#define KEYBOARD_DETECT_GROUP10_PORT PA
#define KEYBOARD_DETECT_GROUP10_PORT_VAL 0
#define KEYBOARD_DETECT_GROUP10_PIN 13
#define KEYBOARD_PRESS_GROUP10 PA12
#define KEYBOARD_PRESS_GROUP10_PORT PA
#define KEYBOARD_PRESS_GROUP10_PORT_VAL 0
#define KEYBOARD_PRESS_GROUP10_PIN 12

#define KEYBOARD_DETECT_GROUP11 PA15
#define KEYBOARD_DETECT_GROUP11_PORT PA
#define KEYBOARD_DETECT_GROUP11_PORT_VAL 0
#define KEYBOARD_DETECT_GROUP11_PIN 15
#define KEYBOARD_PRESS_GROUP11 PA14
#define KEYBOARD_PRESS_GROUP11_PORT PA
#define KEYBOARD_PRESS_GROUP11_PORT_VAL 0
#define KEYBOARD_PRESS_GROUP11_PIN 14

typedef enum
{
	KEYBOARD_KEY_RELEASE,
	KEYBOARD_KEY_DETECT,
	KEYBOARD_KEY_PRESS,
} KEYBOARD_PRESS_STATUS_T;

typedef struct
{
	KEYBOARD_PRESS_STATUS_T status;
	uint32_t detect_tick;
	uint16_t velocity;
} KEYBOARD_KEY_STATUS_T;

static KEYBOARD_KEY_STATUS_T _keyboard_status[KEYBOARD_TOTAL_KEYS];
volatile uint32_t _velocity_tick = 0;
static keyboard_event_callback _keyboard_callback = NULL;

void TMR1_IRQHandler(void)
{
	TIMER_ClearIntFlag(KEYBOARD_TIMER);
	++_velocity_tick;
}

void keyboard_init()
{
	// setup keys
	GPIO_SetMode(KEYBOARD_KEY1_PORT, 1 << KEYBOARD_KEY1_PIN, GPIO_PMD_OUTPUT);
	GPIO_SetMode(KEYBOARD_KEY2_PORT, 1 << KEYBOARD_KEY2_PIN, GPIO_PMD_OUTPUT);
	GPIO_SetMode(KEYBOARD_KEY3_PORT, 1 << KEYBOARD_KEY3_PIN, GPIO_PMD_OUTPUT);
	GPIO_SetMode(KEYBOARD_KEY4_PORT, 1 << KEYBOARD_KEY4_PIN, GPIO_PMD_OUTPUT);
	GPIO_SetMode(KEYBOARD_KEY5_PORT, 1 << KEYBOARD_KEY5_PIN, GPIO_PMD_OUTPUT);
	GPIO_SetMode(KEYBOARD_KEY6_PORT, 1 << KEYBOARD_KEY6_PIN, GPIO_PMD_OUTPUT);
	GPIO_SetMode(KEYBOARD_KEY7_PORT, 1 << KEYBOARD_KEY7_PIN, GPIO_PMD_OUTPUT);
	GPIO_SetMode(KEYBOARD_KEY8_PORT, 1 << KEYBOARD_KEY8_PIN, GPIO_PMD_OUTPUT);

	// set key pins high
	GPIO_PIN_DATA(KEYBOARD_KEY1_PORT_VAL, KEYBOARD_KEY1_PIN) = 0;
	GPIO_PIN_DATA(KEYBOARD_KEY2_PORT_VAL, KEYBOARD_KEY2_PIN) = 0;
	GPIO_PIN_DATA(KEYBOARD_KEY3_PORT_VAL, KEYBOARD_KEY3_PIN) = 0;
	GPIO_PIN_DATA(KEYBOARD_KEY4_PORT_VAL, KEYBOARD_KEY4_PIN) = 0;
	GPIO_PIN_DATA(KEYBOARD_KEY5_PORT_VAL, KEYBOARD_KEY5_PIN) = 0;
	GPIO_PIN_DATA(KEYBOARD_KEY6_PORT_VAL, KEYBOARD_KEY6_PIN) = 0;
	GPIO_PIN_DATA(KEYBOARD_KEY7_PORT_VAL, KEYBOARD_KEY7_PIN) = 0;
	GPIO_PIN_DATA(KEYBOARD_KEY8_PORT_VAL, KEYBOARD_KEY8_PIN) = 0;

	// setup groups
	GPIO_SetMode(KEYBOARD_DETECT_GROUP1_PORT, 1 << KEYBOARD_DETECT_GROUP1_PIN, GPIO_PMD_INPUT);
	GPIO_SetMode(KEYBOARD_PRESS_GROUP1_PORT, 1 << KEYBOARD_PRESS_GROUP1_PIN, GPIO_PMD_INPUT);
	GPIO_SetMode(KEYBOARD_DETECT_GROUP2_PORT, 1 << KEYBOARD_DETECT_GROUP2_PIN, GPIO_PMD_INPUT);
	GPIO_SetMode(KEYBOARD_PRESS_GROUP2_PORT, 1 << KEYBOARD_PRESS_GROUP2_PIN, GPIO_PMD_INPUT);
	GPIO_SetMode(KEYBOARD_DETECT_GROUP3_PORT, 1 << KEYBOARD_DETECT_GROUP3_PIN, GPIO_PMD_INPUT);
	GPIO_SetMode(KEYBOARD_PRESS_GROUP3_PORT, 1 << KEYBOARD_PRESS_GROUP3_PIN, GPIO_PMD_INPUT);
	GPIO_SetMode(KEYBOARD_DETECT_GROUP4_PORT, 1 << KEYBOARD_DETECT_GROUP4_PIN, GPIO_PMD_INPUT);
	GPIO_SetMode(KEYBOARD_PRESS_GROUP4_PORT, 1 << KEYBOARD_PRESS_GROUP4_PIN, GPIO_PMD_INPUT);
	GPIO_SetMode(KEYBOARD_DETECT_GROUP5_PORT, 1 << KEYBOARD_DETECT_GROUP5_PIN, GPIO_PMD_INPUT);
	GPIO_SetMode(KEYBOARD_PRESS_GROUP5_PORT, 1 << KEYBOARD_PRESS_GROUP5_PIN, GPIO_PMD_INPUT);
	GPIO_SetMode(KEYBOARD_DETECT_GROUP6_PORT, 1 << KEYBOARD_DETECT_GROUP6_PIN, GPIO_PMD_INPUT);
	GPIO_SetMode(KEYBOARD_PRESS_GROUP6_PORT, 1 << KEYBOARD_PRESS_GROUP6_PIN, GPIO_PMD_INPUT);
	GPIO_SetMode(KEYBOARD_DETECT_GROUP7_PORT, 1 << KEYBOARD_DETECT_GROUP7_PIN, GPIO_PMD_INPUT);
	GPIO_SetMode(KEYBOARD_PRESS_GROUP7_PORT, 1 << KEYBOARD_PRESS_GROUP7_PIN, GPIO_PMD_INPUT);
	GPIO_SetMode(KEYBOARD_DETECT_GROUP8_PORT, 1 << KEYBOARD_DETECT_GROUP8_PIN, GPIO_PMD_INPUT);
	GPIO_SetMode(KEYBOARD_PRESS_GROUP8_PORT, 1 << KEYBOARD_PRESS_GROUP8_PIN, GPIO_PMD_INPUT);
	GPIO_SetMode(KEYBOARD_DETECT_GROUP9_PORT, 1 << KEYBOARD_DETECT_GROUP9_PIN, GPIO_PMD_INPUT);
	GPIO_SetMode(KEYBOARD_PRESS_GROUP9_PORT, 1 << KEYBOARD_PRESS_GROUP9_PIN, GPIO_PMD_INPUT);
	GPIO_SetMode(KEYBOARD_DETECT_GROUP10_PORT, 1 << KEYBOARD_DETECT_GROUP10_PIN, GPIO_PMD_INPUT);
	GPIO_SetMode(KEYBOARD_PRESS_GROUP10_PORT, 1 << KEYBOARD_PRESS_GROUP10_PIN, GPIO_PMD_INPUT);
	GPIO_SetMode(KEYBOARD_DETECT_GROUP11_PORT, 1 << KEYBOARD_DETECT_GROUP11_PIN, GPIO_PMD_INPUT);
	GPIO_SetMode(KEYBOARD_PRESS_GROUP11_PORT, 1 << KEYBOARD_PRESS_GROUP11_PIN, GPIO_PMD_INPUT);

	memset(_keyboard_status, 0, sizeof(_keyboard_status));

	// setup velocity timer
	CLK_EnableModuleClock(KEYBOARD_TIMER_MODULE);
	CLK_SetModuleClock(KEYBOARD_TIMER_MODULE, CLK_CLKSEL1_TMR1_S_HIRC, 0);

	TIMER_Open(KEYBOARD_TIMER, TIMER_PERIODIC_MODE, KEYBOARD_VELOCITY_RATE_MS);
	TIMER_EnableInt(KEYBOARD_TIMER);
	NVIC_EnableIRQ(TMR1_IRQn);
	TIMER_Start(KEYBOARD_TIMER);
}

void keyboard_scan_keys(uint32_t detect_port, uint32_t detect_pin, uint32_t press_port, uint32_t press_pin, uint32_t group)
{
	volatile uint32_t delay;
	uint32_t mask = 0x0100;
	uint32_t key_index = (group - 1) * 8;

	for(uint32_t i=0; i<8; i++)
	{
		// set key pin
		PB->DOUT |= mask;

		KEYBOARD_DELAY();

		if(GPIO_PIN_DATA(detect_port, detect_pin))
		{
			if(_keyboard_status[key_index].status == KEYBOARD_KEY_RELEASE)
			{
				_keyboard_status[key_index].status = KEYBOARD_KEY_DETECT;
				_keyboard_status[key_index].detect_tick = _velocity_tick;
			}
			else if(_keyboard_status[key_index].status == KEYBOARD_KEY_DETECT)
			{
				if(GPIO_PIN_DATA(press_port, press_pin))
				{
					_keyboard_status[key_index].status = KEYBOARD_KEY_PRESS;

					int32_t velocity = _velocity_tick - _keyboard_status[key_index].detect_tick;

					// signal press
					_keyboard_callback(KEYBOARD_EVENT_PRESS, KEYBOARD_START_NOTE + key_index, velocity);
				}
			}
		}
		else
		{
			if(_keyboard_status[key_index].status == KEYBOARD_KEY_PRESS)
			{
				// signal release
				_keyboard_callback(KEYBOARD_EVENT_RELEASE, KEYBOARD_START_NOTE + key_index, 0);
			}

			_keyboard_status[key_index].status = KEYBOARD_KEY_RELEASE;
		}

		// clear key pin
		PB->DOUT &= ~mask;

		mask <<= 1;
		key_index++;
	}
}

void keyboard_task()
{
	keyboard_scan_keys(KEYBOARD_DETECT_GROUP1_PORT_VAL, KEYBOARD_DETECT_GROUP1_PIN, KEYBOARD_PRESS_GROUP1_PORT_VAL, KEYBOARD_PRESS_GROUP1_PIN, 1);
	keyboard_scan_keys(KEYBOARD_DETECT_GROUP2_PORT_VAL, KEYBOARD_DETECT_GROUP2_PIN, KEYBOARD_PRESS_GROUP2_PORT_VAL, KEYBOARD_PRESS_GROUP2_PIN, 2);
	keyboard_scan_keys(KEYBOARD_DETECT_GROUP3_PORT_VAL, KEYBOARD_DETECT_GROUP3_PIN, KEYBOARD_PRESS_GROUP3_PORT_VAL, KEYBOARD_PRESS_GROUP3_PIN, 3);
	keyboard_scan_keys(KEYBOARD_DETECT_GROUP4_PORT_VAL, KEYBOARD_DETECT_GROUP4_PIN, KEYBOARD_PRESS_GROUP4_PORT_VAL, KEYBOARD_PRESS_GROUP4_PIN, 4);
	keyboard_scan_keys(KEYBOARD_DETECT_GROUP5_PORT_VAL, KEYBOARD_DETECT_GROUP5_PIN, KEYBOARD_PRESS_GROUP5_PORT_VAL, KEYBOARD_PRESS_GROUP5_PIN, 5);
	keyboard_scan_keys(KEYBOARD_DETECT_GROUP6_PORT_VAL, KEYBOARD_DETECT_GROUP6_PIN, KEYBOARD_PRESS_GROUP6_PORT_VAL, KEYBOARD_PRESS_GROUP6_PIN, 6);
	keyboard_scan_keys(KEYBOARD_DETECT_GROUP7_PORT_VAL, KEYBOARD_DETECT_GROUP7_PIN, KEYBOARD_PRESS_GROUP7_PORT_VAL, KEYBOARD_PRESS_GROUP7_PIN, 7);
	keyboard_scan_keys(KEYBOARD_DETECT_GROUP8_PORT_VAL, KEYBOARD_DETECT_GROUP8_PIN, KEYBOARD_PRESS_GROUP8_PORT_VAL, KEYBOARD_PRESS_GROUP8_PIN, 8);
	keyboard_scan_keys(KEYBOARD_DETECT_GROUP9_PORT_VAL, KEYBOARD_DETECT_GROUP9_PIN, KEYBOARD_PRESS_GROUP9_PORT_VAL, KEYBOARD_PRESS_GROUP9_PIN, 9);
	keyboard_scan_keys(KEYBOARD_DETECT_GROUP10_PORT_VAL, KEYBOARD_DETECT_GROUP10_PIN, KEYBOARD_PRESS_GROUP10_PORT_VAL, KEYBOARD_PRESS_GROUP10_PIN, 10);
	keyboard_scan_keys(KEYBOARD_DETECT_GROUP11_PORT_VAL, KEYBOARD_DETECT_GROUP11_PIN, KEYBOARD_PRESS_GROUP11_PORT_VAL, KEYBOARD_PRESS_GROUP11_PIN, 11);
}

void keyboard_register_callback(keyboard_event_callback callback)
{
	_keyboard_callback = callback;
}
