/*
 * midi_spec.h
 *
 *  Created on: Sep 18, 2023
 *      Author: matt
 */

#ifndef MIDI_SPEC_H_
#define MIDI_SPEC_H_

#include <stdint.h>

#define TOTAL_CABLES 16
#define TOTAL_CHANNELS 16

// ==============================================
// MIDI 1.0 CIN VALUES
// ==============================================
#define CIN_MISC 0x0
#define CIN_CABLE_EVENT 0x1
#define CIN_TWO_BYTE_COMMON 0x2
#define CIN_THREE_BYTE_COMMON 0x3
#define CIN_SYSEX_START 0x4
#define CIN_SINGLE_BYTE_COMMON_OR_SYSEX_END_ONE 0x5
#define CIN_SYSEX_END_TWO 0x6
#define CIN_SYSEX_END_THREE 0x7
#define CIN_NOTE_OFF 0x8
#define CIN_NOTE_ON 0x9
#define CIN_POLY_KEY_PRESS 0xA
#define CIN_CONTROL_CHANGE 0xB
#define CIN_PROGRAM_CHANGE 0xC
#define CIN_CHANNEL_PRESSURE 0xD
#define CIN_PITCH_BEND 0xE
#define CIN_SINGLE_BYTE 0xF
#define CIN_MASK 0x0F

// ==============================================
// MIDI 2.0 MESSAGE TYPE
// ==============================================
#define MIDI20_MESSAGE_TYPE_UTILITY 0x00
#define MIDI20_MESSAGE_TYPE_SYSTEM 0x10
#define MIDI20_MESSAGE_TYPE_10_CHANNEL_VOICE 0x20
#define MIDI20_MESSAGE_TYPE_DATA64 0x30
#define MIDI20_MESSAGE_TYPE_20_CHANNEL_VOICE 0x40
#define MIDI20_MESSAGE_TYPE_DATA128 0x50
#define MIDI20_MESSAGE_TYPE_FLEX 0xD0
#define MIDI20_MESSAGE_TYPE_STREAM 0xF0

// ==============================================
// MIDI 2.0 SYSEX STATUS
// ==============================================
#define MIDI20_SYSEX_STATUS_COMPLETE_IN_1 0x00
#define MIDI20_SYSEX_STATUS_START 0x10
#define MIDI20_SYSEX_STATUS_CONTINUE 0x20
#define MIDI20_SYSEX_STATUS_STOP 0x30

// ==============================================
// MIDI 2.0 STREAM STATUS
// ==============================================
#define MIDI20_STREAM_STATUS_COMPLETE_IN_1 0x00
#define MIDI20_STREAM_STATUS_START 0x04
#define MIDI20_STREAM_STATUS_CONTINUE 0x08
#define MIDI20_STREAM_STATUS_STOP 0x0C

// ==============================================
// MIDI 2.0 CI
// ==============================================
#define MIDI20_UNIVERSAL_SYSEX 0x7E
#define MIDI20_UNIVERSAL_SYSEX_SUBID1_CI 0x0D
#define MIDI20_UNIVERSAL_SYSEX_SUBID2_INQUIRY_PROP_EX_CAPS 0x30
#define MIDI20_UNIVERSAL_SYSEX_SUBID2_INQUIRY_PROP_EX_CAPS_REPLY 0x31
#define MIDI20_UNIVERSAL_SYSEX_SUBID2_INQUIRY_PROP_EX_GET 0x34
#define MIDI20_UNIVERSAL_SYSEX_SUBID2_INQUIRY_PROP_EX_GET_REPLY 0x35
#define MIDI20_UNIVERSAL_SYSEX_SUBID2_INQUIRY_PROP_EX_SET 0x36
#define MIDI20_UNIVERSAL_SYSEX_SUBID2_INQUIRY_PROP_EX_SET_REPLY 0x37
#define MIDI20_UNIVERSAL_SYSEX_SUBID2_DISCOVERY 0x70
#define MIDI20_UNIVERSAL_SYSEX_SUBID2_DISCOVERY_REPLY 0x71
#define MIDI20_UNIVERSAL_SYSEX_SUBID2_INQUIRY_ENDPOINT 0x72
#define MIDI20_UNIVERSAL_SYSEX_SUBID2_INQUIRY_ENDPOINT_REPLY 0x73
#define MIDI20_UNIVERSAL_SYSEX_SUBID2_ACK 0x7D
#define MIDI20_UNIVERSAL_SYSEX_SUBID2_NAK 0x7F

#define MIDI20_CI_CATEGORY_PROFILE_CONFIG 0x04
#define MIDI20_CI_CATEGORY_PROPERTY_EXCHANGE 0x08
#define MIDI20_CI_CATEGORY_PROCESS_INQUIRY 0x10

#define MIDI20_CI_NAK_STATUS_CODE_NAK 0x00
#define MIDI20_CI_NAK_STATUS_CODE_CI_MESSAGE_NOT_SUPPORTED 0x01
#define MIDI20_CI_NAK_STATUS_CODE_CI_VERSION_NOT_SUPPORTED 0x02
#define MIDI20_CI_NAK_STATUS_CODE_CGF_NOT_IN_USE 0x03
#define MIDI20_CI_NAK_STATUS_CODE_PROFILE_NOT_SUPPORTED 0x04
#define MIDI20_CI_NAK_STATUS_CODE_TERMINATE_INQUIRY 0x20
#define MIDI20_CI_NAK_STATUS_CODE_PROPERTY_EX_OUT_OF_SEQ 0x21
#define MIDI20_CI_NAK_STATUS_CODE_ERROR_RETRY 0x40
#define MIDI20_CI_NAK_STATUS_CODE_MESSAGE_MALFORMED 0x41
#define MIDI20_CI_NAK_STATUS_CODE_TIMEOUT_OCCURRED 0x42
#define MIDI20_CI_NAK_STATUS_CODE_BUSY 0x43

#define MIDI20_CI_ACK_STATUS_CODE_ACK 0x00

// ==============================================
// Commands
// ==============================================
#define MIDI_COMMAND_MASK 0xF0
#define MIDI_NOTE_OFF 0x80
#define MIDI_NOTE_ON 0x90
#define MIDI_AFTERTOUCH 0xA0
#define MIDI_CONTROLLER 0xB0
#define MIDI_PROGRAM_CHANGE 0xC0
#define MIDI_CHANNEL_PRESSURE 0xD0
#define MIDI_PITCH_WHEEL 0xE0
#define MIDI_OTHER 0xF0
#define MIDI_SYSEX_START 0xF0
#define MIDI_QUARTER_FRAME_MESSAGE 0xF1
#define MIDI_SONG_POSITION_POINTER 0xF2
#define MIDI_SONG_SELECT 0xF3
#define MIDI_TUNE_REQUEST 0xF6
#define MIDI_SYSEX_END 0xF7
#define MIDI_CLOCK 0xF8
#define MIDI_START 0xFA
#define MIDI_CONTINUE 0xFB
#define MIDI_STOP 0xFC
#define MIDI_SENSE 0xFE
#define MIDI_RESET 0xFF

// ==============================================
// Controllers
// ==============================================
#define MIDI_CONT_BANK_SELECT 0
#define MIDI_CONT_MOD_WHEEL_COARSE 1
#define MIDI_CONT_BREATH_CONTROLLER_COARSE 2
#define MIDI_CONT_FOOT_PEDAL_COARSE 4
#define MIDI_CONT_PORTAMENTO_TIME_COARSE 5
#define MIDI_CONT_DATA_ENTRY_COARSE 6
#define MIDI_CONT_VOLUME_COARSE 7
#define MIDI_CONT_BALANCE_COARSE 8
#define MIDI_CONT_PAN_POSITION_COARSE 10
#define MIDI_CONT_EXPRESSION_COARSE 11
#define MIDI_CONT_EFFECT_CONTROL_1_COARSE 12
#define MIDI_CONT_EFFECT_CONTROL_2_COARSE 13
#define MIDI_CONT_GEN_PURPOSE_SLIDER_1 16
#define MIDI_CONT_GEN_PURPOSE_SLIDER_2 17
#define MIDI_CONT_GEN_PURPOSE_SLIDER_3 18
#define MIDI_CONT_GEN_PURPOSE_SLIDER_4 19
#define MIDI_CONT_BANK_SELECT_FINE 32
#define MIDI_CONT_MOD_WHEEL_FINE 33
#define MIDI_CONT_BREATH_CONTROLLER_FINE 34
#define MIDI_CONT_FOOT_PEDAL_FINE 36
#define MIDI_CONT_PORTAMENTO_TIME_FINE 37
#define MIDI_CONT_DATA_ENTRY_FINE 38
#define MIDI_CONT_VOLUME_FINE 39
#define MIDI_CONT_BALANCE_FINE 40
#define MIDI_CONT_PAN_POSITION_FINE 42
#define MIDI_CONT_EXPRESSION_FINE 43
#define MIDI_CONT_EFFECT_CONTROL_1_FINE 44
#define MIDI_CONT_EFFECT_CONTROL_2_FINE 45
#define MIDI_CONT_GEN_PURPOSE_SLIDER_1_FINE 48
#define MIDI_CONT_GEN_PURPOSE_SLIDER_2_FINE 49
#define MIDI_CONT_GEN_PURPOSE_SLIDER_3_FINE 50
#define MIDI_CONT_GEN_PURPOSE_SLIDER_4_FINE 51
#define MIDI_CONT_HOLD_PEDAL 64
#define MIDI_CONT_PORTAMENTO 65
#define MIDI_CONT_SUSTENUTO_PEDAL 66
#define MIDI_CONT_SOFT_PEDAL 67
#define MIDI_CONT_LEGATO_PEDAL 68
#define MIDI_CONT_HOLD_2_PEDAL 69
#define MIDI_CONT_SOUND_CONTROLLER_1 70
#define MIDI_CONT_SOUND_CONTROLLER_2 71
#define MIDI_CONT_SOUND_CONTROLLER_3 72
#define MIDI_CONT_SOUND_CONTROLLER_4 73
#define MIDI_CONT_SOUND_CONTROLLER_5 74
#define MIDI_CONT_SOUND_CONTROLLER_6 75
#define MIDI_CONT_SOUND_CONTROLLER_7 76
#define MIDI_CONT_SOUND_CONTROLLER_8 77
#define MIDI_CONT_SOUND_CONTROLLER_9 78
#define MIDI_CONT_SOUND_CONTROLLER_10 79
#define MIDI_CONT_GEN_PURPOSE_CONTROLLER_5 80
#define MIDI_CONT_GEN_PURPOSE_CONTROLLER_6 81
#define MIDI_CONT_GEN_PURPOSE_CONTROLLER_7 82
#define MIDI_CONT_GEN_PURPOSE_CONTROLLER_8 83
#define MIDI_CONT_PORTAMENTO2 84
#define MIDI_CONT_HIGH_RES_VELOCITY_PREFIX 88
#define MIDI_CONT_EFFECTS_1_DEPTH 91
#define MIDI_CONT_EFFECTS_2_DEPTH 92
#define MIDI_CONT_EFFECTS_3_DEPTH 93
#define MIDI_CONT_EFFECTS_4_DEPTH 94
#define MIDI_CONT_EFFECTS_5_DEPTH 95
#define MIDI_CONT_DATA_INCREMENT 96
#define MIDI_CONT_DATA_DECREMENT 97
#define MIDI_CONT_NON_REGISTERED_PARAMETER_COARSE 98
#define MIDI_CONT_NON_REGISTERED_PARAMETER_FINE 99
#define MIDI_CONT_REGISTERED_PARAMETER_COARSE 100
#define MIDI_CONT_REGISTERED_PARAMETER_FINE 101
#define MIDI_CONT_ALL_SOUND_OFF 120
#define MIDI_CONT_RESET_ALL_CONTROLLERS 121
#define MIDI_CONT_LOCAL_CONTROL 122
#define MIDI_CONT_ALL_NOTES_OFF 123
#define MIDI_CONT_ONMI_MODE_OFF 124
#define MIDI_CONT_ONMI_MODE_ON 125
#define MIDI_CONT_MONO_MODE_ON 126
#define MIDI_CONT_POLY_MODE_ON 127

typedef void (*message_callback)(uint8_t group, uint8_t status, uint8_t byte_2, uint8_t byte_3);
typedef void (*sysex_callback)(uint8_t cable, uint8_t *pbytes, uint32_t length);

#endif /* MIDI_SPEC_H_ */
